Repository AY1920S2-CS2103T-F09-2/main, pull requests merged in 2020-03, with the labels that each got.

#88 Added reminder command
  src/main/java/seedu/jelphabot/logic/commands/ReminderCommand.java
  src/main/java/seedu/jelphabot/logic/parser/JelphaBotParser.java
  src/main/java/seedu/jelphabot/model/task/ReminderPredicate.java
  src/test/java/seedu/jelphabot/logic/commands/ReminderCommandTest.java
Labels: type.Enhancement

#128 Updated Calendar Command and CalendarTaskList Components (UI not done)
  src/main/java/seedu/jelphabot/logic/LogicManager.java
  src/main/java/seedu/jelphabot/logic/commands/CalendarCommand.java
  src/main/java/seedu/jelphabot/logic/parser/CalendarCommandParser.java
  src/main/java/seedu/jelphabot/model/Model.java
  src/main/java/seedu/jelphabot/model/ModelManager.java
  src/main/java/seedu/jelphabot/model/task/DateTimeContainsDatePredicate.java
  src/main/java/seedu/jelphabot/ui/MainWindow.java
  src/main/java/seedu/jelphabot/ui/TaskCard.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, type.Story

#142 Update productivity panel
  src/main/java/seedu/jelphabot/commons/core/Messages.java
  src/main/java/seedu/jelphabot/logic/Logic.java
  src/main/java/seedu/jelphabot/logic/LogicManager.java
  src/main/java/seedu/jelphabot/logic/commands/AddCommand.java
  src/main/java/seedu/jelphabot/logic/commands/ClearCommand.java
  src/main/java/seedu/jelphabot/logic/commands/DeleteCommand.java
  src/main/java/seedu/jelphabot/logic/commands/DoneCommand.java
  src/main/java/seedu/jelphabot/logic/commands/EditCommand.java
  src/main/java/seedu/jelphabot/logic/commands/StartTimerCommand.java
  src/main/java/seedu/jelphabot/logic/commands/StopTimerCommand.java
  src/main/java/seedu/jelphabot/logic/parser/AddCommandParser.java
  src/main/java/seedu/jelphabot/model/Model.java
  src/main/java/seedu/jelphabot/model/ModelManager.java
  src/main/java/seedu/jelphabot/model/productivity/Productivity.java
  src/main/java/seedu/jelphabot/model/productivity/ProductivityList.java
  src/main/java/seedu/jelphabot/model/productivity/RunningTimer.java
  src/main/java/seedu/jelphabot/model/productivity/TasksCompleted.java
  src/main/java/seedu/jelphabot/model/productivity/TimeSpentToday.java
  src/main/java/seedu/jelphabot/model/task/Task.java
  src/main/java/seedu/jelphabot/model/util/SampleDataUtil.java
  src/main/java/seedu/jelphabot/storage/JsonAdaptedTask.java
  src/main/java/seedu/jelphabot/ui/MainWindow.java
  src/main/java/seedu/jelphabot/ui/ProductivityCard.java
  src/main/java/seedu/jelphabot/ui/ProductivityPanel.java
  src/main/resources/view/CalendarDayCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProductivityCard.fxml
  src/main/resources/view/ProductivityPanel.fxml
  src/main/resources/view/SortedTaskListPanel.fxml
  src/test/java/seedu/jelphabot/logic/commands/AddCommandTest.java
  src/test/java/seedu/jelphabot/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/jelphabot/testutil/TaskBuilder.java
Labels: priority.High, type.Story

#162 add progressbar to panel
  src/main/java/seedu/jelphabot/model/productivity/TasksCompleted.java
  src/main/java/seedu/jelphabot/model/productivity/TimeSpentToday.java
  src/main/java/seedu/jelphabot/model/task/Task.java
  src/main/java/seedu/jelphabot/ui/ProductivityCard.java
  src/main/java/seedu/jelphabot/ui/ProductivityPanel.java
  src/main/resources/view/ProductivityCard.fxml
Labels: type.Enhancement, type.Story

#173 Update main window display
  src/main/java/seedu/jelphabot/logic/commands/DoneCommand.java
  src/main/java/seedu/jelphabot/logic/commands/EditCommand.java
  src/main/java/seedu/jelphabot/logic/commands/StartTimerCommand.java
  src/main/java/seedu/jelphabot/logic/commands/StopTimerCommand.java
  src/main/java/seedu/jelphabot/logic/parser/AddCommandParser.java
  src/main/java/seedu/jelphabot/logic/parser/JelphaBotParser.java
  src/main/java/seedu/jelphabot/model/productivity/TimeSpentToday.java
  src/main/java/seedu/jelphabot/model/task/Task.java
  src/main/java/seedu/jelphabot/model/task/TimeSpent.java
  src/main/java/seedu/jelphabot/model/util/SampleDataUtil.java
  src/main/java/seedu/jelphabot/storage/JsonAdaptedTask.java
  src/main/java/seedu/jelphabot/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonJelphaBotStorageTest/invalidAndValidTaskJelphaBot.json
  src/test/data/JsonJelphaBotStorageTest/invalidTaskJelphaBot.json
  src/test/data/JsonSerializableJelphaBotTest/duplicateTaskJelphaBot.json
  src/test/data/JsonSerializableJelphaBotTest/invalidTaskJelphaBot.json
  src/test/data/JsonSerializableJelphaBotTest/typicalTasksJelphaBot.json
  src/test/java/seedu/jelphabot/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/jelphabot/testutil/TaskBuilder.java
  src/test/java/seedu/jelphabot/testutil/TypicalTasks.java
Labels: type.Enhancement

#174 updated CalendarCommand to link with UI
  src/main/java/seedu/jelphabot/logic/commands/CalendarCommand.java
  src/main/java/seedu/jelphabot/logic/parser/CalendarCommandParser.java
  src/main/java/seedu/jelphabot/model/task/predicates/TaskDueWithinDayPredicate.java
  src/main/java/seedu/jelphabot/ui/CalendarDayCard.java
  src/main/java/seedu/jelphabot/ui/CalendarPanel.java
  src/main/java/seedu/jelphabot/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/jelphabot/logic/commands/CalendarCommandTest.java
Labels: priority.Medium, type.Enhancement, type.Story

#177 Finished up Calendar Command
  src/main/java/seedu/jelphabot/commons/core/Messages.java
  src/main/java/seedu/jelphabot/commons/util/AppUtil.java
  src/main/java/seedu/jelphabot/logic/commands/CalendarCommand.java
  src/main/java/seedu/jelphabot/logic/parser/CalendarCommandParser.java
  src/main/java/seedu/jelphabot/model/calendar/CalendarDate.java
  src/main/java/seedu/jelphabot/model/task/predicates/TaskDueWithinDayPredicate.java
  src/main/java/seedu/jelphabot/ui/CalendarDayCard.java
  src/main/java/seedu/jelphabot/ui/CalendarPanel.java
  src/test/java/seedu/jelphabot/logic/commands/CalendarCommandTest.java
Labels: priority.High, priority.Medium, type.Enhancement
